### ISSUE TITLE
regex documentation for python

### ISSUE THREAD

**Issue by taidura** [north-pikmin/knowledge#2]
# Objective

 A regex page is to be created in order to give a very overall view of what regex are and how I have used them in actual projects in python, and how they can be used a lot more generally in other contexts.

After reading the regex page, a user should be able to know a bit better what regex is, and know very basic syntax. For more advanced syntax, he/she should be able to refer to this page to get both syntax help and associated detailed examples.

# Tasks

- [x] Regex overview, and how it works behind the scene, 
   - [x] What is a regex? 
   - [x] Where are regex actually used?
   - [x] What actually happens when you try to match a regex pattern in a string?
   - [x] Advantages and limits of regex
- [ ] Regex syntax and applications in python
   - [x] Quick introduction to re
   - [ ] Back and forth between explanation of regex syntax and examples in python
- [ ] A few exercises to try on your own!
